### PR TITLE
Updated Limits: Video features availability

### LINKED ISSUE #130: Video features availability limits were improved recently
Currently:
```
only 30 first participants can cast and see videos of each other, all the later ones will be in a voice-only chat
```

Improved:
```
Up to 30 participants can broadcast, up to 1000 participants can watch, and an unlimited number of participants can listen
```

View the change notes from Telegram
Source: https://telegram.org/blog/video-1000

image

### PR DESCRIPTION
**Pull request by EmilyLove26**
Updated limits to fix #130

### CODE REVIEW

**Comment by Sominemo** [comment]
Hi! I'm incredibly grateful for your help, I'm afraid I'm bit tight with my schedule right now and I will review your change better. Thanks a lot! :)

**Comment by EmilyLove26** [comment]
No worries. Have a good week!

**Comment by Sominemo** [comment]
Thank you for your pull request, I'll implement the changes in my own commit

**Comment by EmilyLove26** [comment]
Sure no problem. Just glad to be able to help in some small way

**Pull request closed without merging**
